import { Bank_Account, Location, Status_Open } from "@prisma/client";
import { prisma } from "../../config/config";

export async function seedRequest() {
  try {
    const request = [
      {
        name: "Budi Santoso",
        vendor_name: "KFC Fried Chicken",
        location: Location.Kantin_Basement,
        open_hour: "08:00",
        close_hour: "20:00",
        email: "kfc@gmail.com",
        phone: "08444444444",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101010",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Michael Surya",
        vendor_name: "MCD Michael Chicken",
        location: Location.Kantin_Payung,
        open_hour: "08:00",
        close_hour: "20:00",
        email: "mcd@gmail.com",
        phone: "083333333333",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101010",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Jane Doe",
        vendor_name: "Burger Queen",
        location: Location.Kantin_Basement,
        open_hour: "09:00",
        close_hour: "21:00",
        email: "burger@gmail.com",
        phone: "08222222222",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101011",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "John Doe",
        vendor_name: "Pizza Hut",
        location: Location.Kantin_Payung,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "pizza@gmail.com",
        phone: "081111111111",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101012",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "Jane Doe",
        vendor_name: "Burger Queen",
        location: Location.Kantin_Basement,
        open_hour: "09:00",
        close_hour: "21:00",
        email: "burger_1@gmail.com",
        phone: "085555555555",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101011",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "John Doe",
        vendor_name: "Pizza Hut",
        location: Location.Kantin_Payung,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "pizza_2@gmail.com",
        phone: "086666666666",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101012",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "Alice Johnson",
        vendor_name: "Sushi World",
        location: Location.Kantin_Basement,
        open_hour: "10:30",
        close_hour: "22:30",
        email: "sushi@gmail.com",
        phone: "081512345678",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101013",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Robert Brown",
        vendor_name: "Steak House",
        location: Location.Kantin_Payung,
        open_hour: "11:00",
        close_hour: "23:00",
        email: "steak@gmail.com",
        phone: "081623456789",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101014",
        bank_type: Bank_Account.Mandiri,
      },
      {
        name: "Emily Davis",
        vendor_name: "Vegan Bites",
        location: Location.Kantin_Basement,
        open_hour: "08:00",
        close_hour: "20:00",
        email: "vegan@gmail.com",
        phone: "081734567890",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101015",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "David Lee",
        vendor_name: "Taco Fiesta",
        location: Location.Kantin_Payung,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "taco@gmail.com",
        phone: "081845678901",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101016",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "Sophia Martinez",
        vendor_name: "Pasta Paradise",
        location: Location.Kantin_Basement,
        open_hour: "09:30",
        close_hour: "21:30",
        email: "pasta@gmail.com",
        phone: "081956789012",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101017",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Daniel Wilson",
        vendor_name: "BBQ Kingdom",
        location: Location.Kantin_Payung,
        open_hour: "11:00",
        close_hour: "23:00",
        email: "bbq@gmail.com",
        phone: "082067890123",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101018",
        bank_type: Bank_Account.Mandiri,
      },
      {
        name: "Olivia Thomas",
        vendor_name: "Healthy Green",
        location: Location.Kantin_Basement,
        open_hour: "08:30",
        close_hour: "20:30",
        email: "healthy@gmail.com",
        phone: "082178901234",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101019",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "Matthew Anderson",
        vendor_name: "Seafood Delight",
        location: Location.Kantin_Payung,
        open_hour: "10:30",
        close_hour: "22:30",
        email: "seafood@gmail.com",
        phone: "082289012345",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101020",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "William Harris",
        vendor_name: "Deli Fresh",
        location: Location.Kantin_Basement,
        open_hour: "09:00",
        close_hour: "21:00",
        email: "deli@gmail.com",
        phone: "082390123456",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101021",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Ava White",
        vendor_name: "Sweet Treats",
        location: Location.Kantin_Payung,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "sweets@gmail.com",
        phone: "082401234567",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101022",
        bank_type: Bank_Account.Mandiri,
      },
      {
        name: "James Clark",
        vendor_name: "Burger Empire",
        location: Location.Kantin_Basement,
        open_hour: "11:00",
        close_hour: "23:00",
        email: "burgerempire@gmail.com",
        phone: "082512345678",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101023",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "Mia Walker",
        vendor_name: "Juice Bar",
        location: Location.Kantin_Payung,
        open_hour: "08:00",
        close_hour: "20:00",
        email: "juice@gmail.com",
        phone: "082623456789",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101024",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "Benjamin Lewis",
        vendor_name: "Fried Chicken Master",
        location: Location.Kantin_Basement,
        open_hour: "09:30",
        close_hour: "21:30",
        email: "chicken@gmail.com",
        phone: "082734567890",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101025",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Tono Sugiarto",
        vendor_name: "Tono Fried Rice",
        location: Location.Kantin_Basement,
        open_hour: "08:00",
        close_hour: "20:00",
        email: "tono@gmail.com",
        phone: "08275555555",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101025",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Josep Marbun",
        vendor_name: "Josep Coffee",
        location: Location.Kantin_Payung,
        open_hour: "09:00",
        close_hour: "21:00",
        email: "josep@gmail.com",
        phone: "08677343842",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101026",
        bank_type: Bank_Account.Mandiri,
      },
      {
        name: "Asep Hidayat",
        vendor_name: "Asep Sate",
        location: Location.Kantin_Basement,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "asep@gmail.com",
        phone: "08567489",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101027",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "Budi Santoso",
        vendor_name: "Budi Martabak",
        location: Location.Kantin_Payung,
        open_hour: "08:30",
        close_hour: "20:30",
        email: "budi@gmail.com",
        phone: "0853467289",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101028",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "Siti Aminah",
        vendor_name: "Siti Bakery",
        location: Location.Kantin_Basement,
        open_hour: "09:00",
        close_hour: "21:00",
        email: "siti@gmail.com",
        phone: "0854367289",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101029",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Rudi Hartono",
        vendor_name: "Rudi Steak",
        location: Location.Kantin_Payung,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "rudi@gmail.com",
        phone: "08123445645",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101030",
        bank_type: Bank_Account.Mandiri,
      },
      {
        name: "Dewi Sartika",
        vendor_name: "Dewi Juice",
        location: Location.Kantin_Basement,
        open_hour: "08:00",
        close_hour: "20:00",
        email: "dewi@gmail.com",
        phone: "0834567890",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101031",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "Ahmad Fauzi",
        vendor_name: "Ahmad Seafood",
        location: Location.Kantin_Payung,
        open_hour: "09:30",
        close_hour: "21:30",
        email: "ahmad@gmail.com",
        phone: "0834567891",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101032",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "Lina Marlina",
        vendor_name: "Lina Dessert",
        location: Location.Kantin_Basement,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "lina@gmail.com",
        phone: "0809999999",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101033",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Ujang Sopian",
        vendor_name: "Ujang Kopi",
        location: Location.Kantin_Payung,
        open_hour: "08:30",
        close_hour: "20:30",
        email: "ujang@gmail.com",
        phone: "0810101010",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101034",
        bank_type: Bank_Account.Mandiri,
      },
      {
        name: "Didi Kasidi",
        vendor_name: "Didi Noodles",
        location: Location.Kantin_Basement,
        open_hour: "09:00",
        close_hour: "21:00",
        email: "didi@gmail.com",
        phone: "084567890124",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101035",
        bank_type: Bank_Account.CIMB,
      },
      {
        name: "Eko Supriyanto",
        vendor_name: "Eko Satay",
        location: Location.Kantin_Payung,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "eko@gmail.com",
        phone: "084567890123",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101036",
        bank_type: Bank_Account.OCBC,
      },
      {
        name: "Joko Riyadi",
        vendor_name: "Joko Tofu",
        location: Location.Kantin_Basement,
        open_hour: "08:00",
        close_hour: "20:00",
        email: "joko@gmail.com",
        phone: "08123456789",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101037",
        bank_type: Bank_Account.BCA,
      },
      {
        name: "Heri Pratama",
        vendor_name: "Heri Donuts",
        location: Location.Kantin_Payung,
        open_hour: "09:30",
        close_hour: "21:30",
        email: "heri@gmail.com",
        phone: "084567890122",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101038",
        bank_type: Bank_Account.Mandiri,
      },
      {
        name: "Tini Susanti",
        vendor_name: "Tini Vegan",
        location: Location.Kantin_Basement,
        open_hour: "10:00",
        close_hour: "22:00",
        email: "tini@gmail.com",
        phone: "084567890121",
        document: "test.pdf",
        proposal: "proposal.pdf",
        photo: "ktp.png",
        bank_account: "48101039",
        bank_type: Bank_Account.CIMB,
      },
    ];

    for (const req of request) {
      await prisma.request.create({
        data: req,
      });
    }
  } catch (error) {}
}
