name: CI QTEENZ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client:
    name: Build Client (React.js with Vite)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        working-directory: ./Client
        run: npm install

      - name: Build Client
        working-directory: ./Client
        env:
          CI: true
        run: npm run build

